const shoes = [
    {
        id: 1,
        category: 'MEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 2,
        category: 'MEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 3,
        category: 'MEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 4,
        category: 'MEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },

    {
        id: 5,
        category: 'MEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 6,
        category: 'MEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 7,
        category: 'WOMEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 8,
        category: 'WOMEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 9,
        category: 'WOMEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 10,
        category: 'WOMEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 11,
        category: 'WOMEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 12,
        category: 'WOMEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 13,
        category: 'KIDS',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 14,
        category: 'KIDS',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 15,
        category: 'KIDS',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 16,
        category: 'KIDS',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 17,
        category: 'KIDS',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 18,
        category: 'KIDS',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 19,
        category: 'MEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 20,
        category: 'MEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 21,
        category: 'MEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },
    {
        id: 22,
        category: 'MEN',
        img: './images/item-1.jpeg',
        rate: '',
        View: '',
    },

]
export default shoes;